# Generated by Django 6.0.4 on 2026-04-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_goodsreceiptnote_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceiptnote',
            old_name='recieved_amount',
            new_name='received_amount',
        ),
        migrations.RenameField(
            model_name='goodsreceiptnote',
            old_name='recieved_at',
            new_name='received_at',
        ),
        migrations.RenameField(
            model_name='goodsreceiptnote',
            old_name='recieved_by',
            new_name='received_by',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='procurement.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='procurement.tenant'),
            preserve_default=False,
        ),
    ]
