# Generated by Django 6.0.4 on 2026-04-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_recieved_amount_goodsreceiptnote_received_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptNote',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
